#!/usr/bin/env bash
#
# Refresh the Public Suffix List and its version file, together.
#
# Together is the whole point. The version file is what makes "stale" a
# question with an answer, and a list refreshed without it — or a version
# edited to match a list nobody re-fetched — is worse than an old list, because
# it reads as though someone checked.
#
#   ci/update-psl.sh           fetch, write both files, report what changed
#   ci/update-psl.sh --check   report whether upstream differs; change nothing
#
# Not run by any gate. The gate asserts that the two files agree with each
# other and that the fetch date is inside a year; it does not reach the network,
# because a gate that depends on publicsuffix.org being up is a gate that goes
# red for reasons nobody here controls.

. "$(dirname "$0")/lib.sh"

SOURCE="https://publicsuffix.org/list/public_suffix_list.dat"
LIST="data/public_suffix_list.dat"
VERSION="data/public_suffix_list.version"

if ! command -v curl >/dev/null 2>&1; then
    echo "FAIL curl is not on PATH" >&2
    exit 1
fi

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

info "fetching $SOURCE"
if ! curl -fsSL -H "User-Agent: pelorus-build" "$SOURCE" -o "$TMP"; then
    echo "FAIL could not fetch the list" >&2
    exit 1
fi

# A truncated download that still exits zero would otherwise be written over a
# good list, and a short list is a wide partition boundary — the failure this
# file exists to prevent. The real list is ~16k lines; 5000 is a floor well
# below it and well above any plausible error page.
lines="$(wc -l < "$TMP" | tr -d ' ')"
if [ "${lines:-0}" -lt 5000 ]; then
    echo "FAIL the fetched list has only $lines lines; refusing to install it" >&2
    exit 1
fi
if ! grep -q "^// ===BEGIN ICANN DOMAINS===" "$TMP"; then
    echo "FAIL the fetched file has no ICANN section marker; it is not the list" >&2
    exit 1
fi

new_sha="$(sha256sum "$TMP" | cut -d' ' -f1)"
old_sha=""
[ -f "$LIST" ] && old_sha="$(sha256sum "$LIST" | cut -d' ' -f1)"

if [ "${1:-}" = "--check" ]; then
    if [ "$new_sha" = "$old_sha" ]; then
        ok "the shipped list matches upstream"
        exit 0
    fi
    echo "FAIL upstream differs from the shipped list; run ci/update-psl.sh" >&2
    exit 1
fi

if [ "$new_sha" = "$old_sha" ]; then
    ok "already current ($new_sha)"
    exit 0
fi

cp "$TMP" "$LIST"
fetched="$(date -u +%Y-%m-%d)"

cat > "$VERSION" <<VERSIONEOF
# Public Suffix List version.
#
# The PSL carries no version number of its own, so this file is the version:
# the SHA-256 of the list as fetched, and the date it was fetched. Both are
# asserted by crates/px-net/tests/psl.rs.
#
# Why this file exists at all. Partitioning is keyed by eTLD+1 (invariant 2),
# so a stale list does not degrade privacy gently - it draws the security
# boundary in the wrong place, and nothing observable breaks. A suffix added
# upstream and missing here means two sites this browser believes are one.
# There is no symptom to notice, which is why staleness has to be measurable
# rather than felt.
#
# Generated by ci/update-psl.sh. Editing either file by hand defeats the
# assertion that they describe each other.

sha256 = "$new_sha"
fetched = "$fetched"
source = "$SOURCE"
VERSIONEOF

ok "updated"
info "  was $old_sha"
info "  now $new_sha"
info "  fetched $fetched"
info "run the gate before committing: cargo test -p px-net --test psl"
