#!/usr/bin/env bash
#
# Refresh the HSTS preload list and its version file, together.
#
# Same discipline as ci/update-psl.sh, for the same reason: the version file is
# what makes "stale" answerable, and a list refreshed without it reads as
# though somebody checked.
#
#   ci/update-hsts.sh           fetch, convert, write both files
#   ci/update-hsts.sh --check   report whether upstream differs; change nothing
#
# # Why a compact form rather than the upstream JSON
#
# Chromium publishes 94,644 entries as a 10.5 MB JSON file with comments. Every
# entry is `mode: force-https` — the field is constant across the whole list —
# and the only other thing this browser needs is whether subdomains are
# included. So the shipped form is one host per line, prefixed with `.` when it
# covers subdomains: 1.5 MB, sorted, and readable without a JSON parser.
#
# The conversion is lossy on purpose and the loss is stated: pinsets, report
# URIs and expect-ct data are dropped. This project does not implement key
# pinning, and shipping data for a feature that does not exist would invite
# somebody to assume it does.
#
# # Why the list matters
#
# Without it, the first request to a preloaded host over plaintext is
# interceptable — the classic sslstrip position. The list is the only thing
# that makes a *first* visit safe, which is precisely the visit no dynamic HSTS
# header can protect.

. "$(dirname "$0")/lib.sh"

if [ -z "$PY_BIN" ]; then
    echo "FAIL no python >= 3.11 on PATH" >&2
    exit 1
fi

SOURCE="https://raw.githubusercontent.com/chromium/chromium/main/net/http/transport_security_state_static.json"
LIST="data/hsts_preload.txt"
VERSION="data/hsts_preload.version"

# The User-Agent deliberately does not name the product. The brand gate
# confines the product name to px-brand, docs/, packaging/, README and the
# workspace manifest, and a build script is none of those.
if ! command -v curl >/dev/null 2>&1; then
    echo "FAIL curl is not on PATH" >&2
    exit 1
fi

TMP_JSON="$(mktemp)"
TMP_LIST="$(mktemp)"
trap 'rm -f "$TMP_JSON" "$TMP_LIST"' EXIT

info "fetching $SOURCE"
if ! curl -fsSL -H "User-Agent: build-data-fetch" "$SOURCE" -o "$TMP_JSON"; then
    echo "FAIL could not fetch the list" >&2
    exit 1
fi

"$PY_BIN" - "$TMP_JSON" "$TMP_LIST" <<'PY'
import json
import re
import sys

source, destination = sys.argv[1], sys.argv[2]
with open(source, encoding="utf-8") as handle:
    raw = handle.read()

# The upstream file is JSON with // comment lines, which json.loads refuses.
stripped = re.sub(r"^\s*//.*$", "", raw, flags=re.M)
entries = json.loads(stripped).get("entries", [])

hosts = []
for entry in entries:
    if entry.get("mode") != "force-https":
        continue
    name = entry.get("name")
    if not name:
        continue
    hosts.append(("." if entry.get("include_subdomains") else "") + name)

if len(hosts) < 10000:
    print(f"FAIL only {len(hosts)} force-https entries; that is not the list", file=sys.stderr)
    sys.exit(1)

hosts.sort()
with open(destination, "w", encoding="utf-8", newline="\n") as handle:
    handle.write("\n".join(hosts) + "\n")
print(f"  {len(hosts)} hosts")
PY

if [ ! -s "$TMP_LIST" ]; then
    echo "FAIL the conversion produced nothing" >&2
    exit 1
fi

new_sha="$(sha256sum "$TMP_LIST" | cut -d' ' -f1)"
old_sha=""
[ -f "$LIST" ] && old_sha="$(sha256sum "$LIST" | cut -d' ' -f1)"

if [ "${1:-}" = "--check" ]; then
    if [ "$new_sha" = "$old_sha" ]; then
        ok "the shipped list matches upstream"
        exit 0
    fi
    echo "FAIL upstream differs from the shipped list; run ci/update-hsts.sh" >&2
    exit 1
fi

if [ "$new_sha" = "$old_sha" ]; then
    ok "already current ($new_sha)"
    exit 0
fi

cp "$TMP_LIST" "$LIST"
count="$(wc -l < "$LIST" | tr -d ' ')"
fetched="$(date -u +%Y-%m-%d)"

cat > "$VERSION" <<VERSIONEOF
# HSTS preload list version.
#
# The list carries no version of its own, so this file is the version: the
# SHA-256 of the converted list and the date it was fetched. Both are asserted
# by crates/px-net/tests/hsts.rs.
#
# Converted from Chromium's transport_security_state_static.json to one host
# per line, prefixed with '.' when it covers subdomains. The conversion is
# lossy on purpose: pinsets and report URIs are dropped, because this browser
# does not implement key pinning and shipping data for a feature that does not
# exist would invite somebody to assume it does.
#
# A stale list is not a broken feature, it is a quiet one. Hosts added upstream
# since this was fetched get no protection on a first visit, which is exactly
# the visit no dynamic HSTS header can cover.
#
# Generated by ci/update-hsts.sh. Editing either file by hand defeats the
# assertion that they describe each other.

sha256 = "$new_sha"
fetched = "$fetched"
hosts = $count
source = "$SOURCE"
VERSIONEOF

ok "updated"
info "  was $old_sha"
info "  now $new_sha"
info "  $count hosts, fetched $fetched"
